version: '3.8'

services:
  cube:
    build: .
    ports:
      - "4002:4000"
    restart: on-failure
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./model/cubes:/cube/model/cubes
      - ./cube.js:/cube/cube.js
      # Ссылается на БД в react-app/public (создается из скрипта)
      - ../react-app/public/database.db:/cube/database.db

  redis:
    image: redis:6
    restart: always